
import { GoogleGenAI, Type } from "@google/genai";
import { GameLevel, WordPair } from "../types";

// Vocabulary data from Units 1-6
const UNIT_WORDS: Record<GameLevel, WordPair[]> = {
  [GameLevel.Unit1]: [
    { en: "name", cn: "名字" },
    { en: "nice", cn: "令人愉快的; 友好的" },
    { en: "ear", cn: "耳朵" },
    { en: "hand", cn: "手" },
    { en: "eye", cn: "眼睛" },
    { en: "mouth", cn: "嘴" },
    { en: "arm", cn: "胳膊" },
    { en: "can", cn: "可以" },
    { en: "share", cn: "分享" },
    { en: "smile", cn: "微笑; 笑" },
    { en: "listen", cn: "听; 倾听" },
    { en: "help", cn: "帮助" },
    { en: "say", cn: "说; 讲" },
    { en: "friend", cn: "朋友" },
    { en: "good", cn: "好的" },
  ],
  [GameLevel.Unit1Supplement]: [
    { en: "I", cn: "我 (主格)" },
    { en: "my", cn: "我的" },
    { en: "we", cn: "我们 (主格)" },
    { en: "our", cn: "我们的" },
    { en: "you", cn: "你, 你们" },
    { en: "your", cn: "你的, 你们的" },
    { en: "me", cn: "我 (宾格)" },
    { en: "us", cn: "我们 (宾格)" },
    { en: "meet", cn: "遇见, 见到" },
    { en: "wave", cn: "挥手, 挥动" },
    { en: "point", cn: "指着, 指出" },
    { en: "thank", cn: "感谢, 谢谢" },
    { en: "play", cn: "玩, 玩耍" },
    { en: "look", cn: "看" },
    { en: "together", cn: "一起" },
    { en: "new", cn: "新的" },
    { en: "let", cn: "让" },
    { en: "what", cn: "什么" },
    { en: "am/is/are", cn: "是" },
  ],
  [GameLevel.Unit2]: [
    { en: "mum", cn: "(口语)妈妈" },
    { en: "dad", cn: "(口语)爸爸; 爹爹" },
    { en: "grandma", cn: "奶奶; 姥姥" },
    { en: "grandpa", cn: "爷爷; 姥爷" },
    { en: "grandfather", cn: "(外)祖父; 爷爷; 姥爷; 外公" },
    { en: "grandmother", cn: "(外)祖母; 奶奶; 姥姥; 外婆" },
    { en: "mother", cn: "母亲; 妈妈" },
    { en: "father", cn: "父亲; 爸爸" },
    { en: "me", cn: "我" },
    { en: "sister", cn: "姐; 妹" },
    { en: "family", cn: "家; 家庭" },
    { en: "have", cn: "有" },
    { en: "big", cn: "大的" },
    { en: "cousin", cn: "堂(表)兄弟; 堂(表)姐妹" },
    { en: "brother", cn: "哥; 弟" },
    { en: "baby", cn: "婴儿" },
    { en: "uncle", cn: "伯父; 叔父; 舅父; 姑父; 姨父" },
    { en: "aunt", cn: "伯母; 婶母; 舅母; 姑母; 姨母" },
    { en: "small", cn: "小的" },
  ],
  [GameLevel.Unit3]: [
    { en: "like", cn: "喜欢" },
    { en: "dog", cn: "狗" },
    { en: "pet", cn: "宠物" },
    { en: "cat", cn: "猫" },
    { en: "fish", cn: "鱼; 鱼肉" },
    { en: "bird", cn: "鸟" },
    { en: "rabbit", cn: "兔" },
    { en: "go", cn: "去; 走" },
    { en: "zoo", cn: "动物园" },
    { en: "fox", cn: "狐狸" },
    { en: "Miss", cn: "(学生对女教师的称呼)老师; 女士" },
    { en: "panda", cn: "大熊猫" },
    { en: "red panda", cn: "小熊猫" },
    { en: "cute", cn: "可爱的" },
    { en: "monkey", cn: "猴子" },
    { en: "tiger", cn: "老虎" },
    { en: "elephant", cn: "大象" },
    { en: "lion", cn: "狮; 狮子" },
    { en: "animal", cn: "动物" },
    { en: "giraffe", cn: "长颈鹿" },
    { en: "tall", cn: "高的" },
    { en: "fast", cn: "快的" },
  ],
  [GameLevel.Unit4]: [
    { en: "apple", cn: "苹果" },
    { en: "banana", cn: "香蕉" },
    { en: "farm", cn: "农场" },
    { en: "air", cn: "空气" },
    { en: "orange", cn: "橙子; 柑橘" },
    { en: "grape", cn: "葡萄" },
    { en: "school", cn: "学校" },
    { en: "garden", cn: "花园" },
    { en: "need", cn: "需要" },
    { en: "water", cn: "给...浇水; 水" },
    { en: "flower", cn: "花; 花朵" },
    { en: "grass", cn: "草; 草地" },
    { en: "plant", cn: "种植; 植物" },
    { en: "new", cn: "新的" },
    { en: "tree", cn: "树" },
    { en: "sun", cn: "阳光; 太阳" },
    { en: "give", cn: "给" },
    { en: "them", cn: "它们; 他/她们" },
  ],
  [GameLevel.Unit5]: [
    { en: "colour", cn: "颜色" },
    { en: "orange", cn: "橙红色; 橙红色的" },
    { en: "green", cn: "绿色; 绿色的" },
    { en: "red", cn: "红色; 红色的" },
    { en: "blue", cn: "蓝色; 蓝色的" },
    { en: "make", cn: "使出现; 做" },
    { en: "purple", cn: "紫色; 紫色的" },
    { en: "brown", cn: "棕色; 棕色的" },
    { en: "bear", cn: "熊" },
    { en: "yellow", cn: "黄色; 黄色的" },
    { en: "duck", cn: "鸭" },
    { en: "sea", cn: "海; 海洋" },
    { en: "some", cn: "一些" },
    { en: "pink", cn: "粉色; 粉色的" },
    { en: "draw", cn: "画" },
    { en: "white", cn: "白色; 白色的" },
    { en: "black", cn: "黑色; 黑色的" },
  ],
  [GameLevel.Unit6]: [
    { en: "old", cn: "(多少)岁; 年纪; 旧的" },
    { en: "five", cn: "五" },
    { en: "year", cn: "年纪; 年" },
    { en: "one", cn: "一" },
    { en: "two", cn: "二" },
    { en: "three", cn: "三" },
    { en: "four", cn: "四" },
    { en: "ten", cn: "十" },
    { en: "six", cn: "六" },
    { en: "seven", cn: "七" },
    { en: "eight", cn: "八" },
    { en: "nine", cn: "九" },
    { en: "o'clock", cn: "(表示整点)...点钟" },
    { en: "cut", cn: "切块" },
    { en: "eat", cn: "吃" },
    { en: "cake", cn: "蛋糕" },
  ],
  [GameLevel.Custom]: [],
};

export const fetchWordPairs = async (level: GameLevel): Promise<WordPair[]> => {
  // If it's a preset unit, return data immediately (no AI needed)
  if (level !== GameLevel.Custom && UNIT_WORDS[level] && UNIT_WORDS[level].length > 0) {
    return UNIT_WORDS[level];
  }

  // Fallback for custom or empty levels (though custom decks are handled in App.tsx)
  return [];
};